name: flutter_demo
description: Material 3 Flutter Demo Showcase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for Material 3 demo
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.6.2
  shared_preferences: ^2.3.4
  dio: ^5.7.0
  intl: ^0.20.0
  timeago: ^3.7.0
  
  # UI components
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  fl_chart: ^0.69.0
  flutter_quill: ^11.4.1
  file_picker: ^8.1.6
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # HTTP & JSON & WebSocket
  http: ^1.2.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  web_socket_channel: ^3.0.1
  
  # Chat functionality
  socket_io_client: ^3.1.2
  crypto: ^3.0.5
  uuid: ^4.5.1
  
  # Media & file handling
  image: ^4.2.0
  path: ^1.9.0
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  
  # Audio recording/playback
  record: ^5.1.2
  audioplayers: ^6.1.0
  
  # Emoji picker
  emoji_picker_flutter: ^3.0.0
  
  # Video player
  video_player: ^2.9.2
  
  # Push notifications
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  
  # Data export
  csv: ^6.0.0
  
  # Calendar functionality
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.4.5
  json_serializable: ^6.9.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true