version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ENABLE_RANDOM_ERRORS=true
      - ERROR_RATE=0.05
      - LOG_LEVEL=INFO
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    restart: unless-stopped